# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  fastapi:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://root:root@mongo:27017/
      - SECRET_KEY=/run/secrets/jwt_secret
      - MAIL_USERNAME=example@mail.com
      - MAIL_PASSWORD=run/secrets/mail_password
      - MAIL_FROM=example@mail.com

    volumes:
      - ./static:/app/static
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

secrets:
  jwt_secret:
    file: secret/jwt_secret.txt
  mail_password:
    file: secret/mail_password